version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: folha-pagamento-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: folha_pagamento
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_data:
